# -*- coding: utf-8 -*-
{
    'name': 'e-MECeF BJ',
    'version': '17.0.1.0',
    'summary': 'Generate Standardized Customer Invoices from the e-MECeF Platform',
    'category': 'Accounting',
    'author': 'GLOBALNET',
    'support': 'support@globalnetsc.com',
    'website': 'https://www.globalnetsc.com',
    'license': 'OPL-1',
    'price': 0,
    'currency': 'USD',
    'data': [
        'security/mecef_security.xml',
        'security/ir.model.access.csv',
        'data/report_paperformat.xml',
        'data/report_templates_inherit.xml',
        'data/mecef_data.xml',
        'views/res_users_view.xml',
        'views/report_invoice.xml',
        'views/account_move_view.xml',
        'views/account_tax_group_view.xml',
        'views/mecef_api_settings.xml',
        'menu/mecef_menu.xml',

    ],
    'depends': ['account'],
    'qweb': [],
    'images': [
        'static/description/mecef_logo.png',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
